/**
Copyright 2017 Frontier Science & Technology Research Foundation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

ADDITIONAL DISCLAIMER:
In addition to the standard warranty exclusions and limitations of 
liability set forth in sections 7, 8 and 9 of the Apache 2.0 license 
that governs the use and development of this software, Frontier Science 
& Technology Research Foundation disclaims any liability for use of 
this software for patient care or in clinical settings. This software 
was developed solely for use in medical and public health research, and 
was not intended, designed, or validated to guide patient care.
*/ 



/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.fstrf.stanfordAsiInterpreter.resistance.grammar.node;

import org.fstrf.stanfordAsiInterpreter.resistance.grammar.analysis.*;

public final class ACondition2 extends PCondition2<ACondition2>
{
    private PLogicsymbol<?> _logicsymbol_;
    private PCondition<?> _condition_;

    public ACondition2()
    {
    }

    public ACondition2(
        PLogicsymbol<?> _logicsymbol_,
        PCondition<?> _condition_)
    {
        setLogicsymbol(_logicsymbol_);

        setCondition(_condition_);

    }
    
    @SuppressWarnings({ "unchecked", "rawtypes" })
	@Override
    public ACondition2 clone()
    {
        return new ACondition2(
            cloneNode((PLogicsymbol) _logicsymbol_),
            cloneNode((PCondition) _condition_));
    }

	@Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACondition2(this);
    }

    public PLogicsymbol<?> getLogicsymbol()
    {
        return _logicsymbol_;
    }

    public void setLogicsymbol(PLogicsymbol<?> node)
    {
        if(_logicsymbol_ != null)
        {
            _logicsymbol_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _logicsymbol_ = node;
    }

    public PCondition<?> getCondition()
    {
        return _condition_;
    }

    public void setCondition(PCondition<?> node)
    {
        if(_condition_ != null)
        {
            _condition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _condition_ = node;
    }

    @SuppressWarnings({ "unchecked", "rawtypes" })
	public String toString()
    {
        return ""
            + toString((PLogicsymbol) _logicsymbol_)
            + toString((PCondition) _condition_);
    }

    void removeChild(Node<?> child)
    {
        if(_logicsymbol_ == child)
        {
            _logicsymbol_ = null;
            return;
        }

        if(_condition_ == child)
        {
            _condition_ = null;
            return;
        }

    }

    <U extends Node<U>> void replaceChild(U oldChild, U newChild)
    {
        if(_logicsymbol_ == oldChild)
        {
            setLogicsymbol((PLogicsymbol<?>) newChild);
            return;
        }

        if(_condition_ == oldChild)
        {
            setCondition((PCondition<?>) newChild);
            return;
        }

    }
}
