/**
Copyright 2017 Frontier Science & Technology Research Foundation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

ADDITIONAL DISCLAIMER:
In addition to the standard warranty exclusions and limitations of 
liability set forth in sections 7, 8 and 9 of the Apache 2.0 license 
that governs the use and development of this software, Frontier Science 
& Technology Research Foundation disclaims any liability for use of 
this software for patient care or in clinical settings. This software 
was developed solely for use in medical and public health research, and 
was not intended, designed, or validated to guide patient care.
*/ 



/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.fstrf.stanfordAsiInterpreter.resistance.grammar.node;

import org.fstrf.stanfordAsiInterpreter.resistance.grammar.analysis.Analysis;

public final class AScorecondition extends PScorecondition<AScorecondition>
{
    private TScore _score_;
    private TFrom _from_;
    private TLPar _lPar_;
    private PScorelist<?> _scorelist_;
    private TRPar _rPar_;

    public AScorecondition()
    {
    }

    public AScorecondition(
        TScore _score_,
        TFrom _from_,
        TLPar _lPar_,
        PScorelist<?> _scorelist_,
        TRPar _rPar_)
    {
        setScore(_score_);

        setFrom(_from_);

        setLPar(_lPar_);

        setScorelist(_scorelist_);

        setRPar(_rPar_);

    }
    
	@Override
    public AScorecondition clone()
    {
        return new AScorecondition(
            (TScore) cloneNode(_score_),
            (TFrom) cloneNode(_from_),
            (TLPar) cloneNode(_lPar_),
            (PScorelist<?>) cloneNode(_scorelist_),
            (TRPar) cloneNode(_rPar_));
    }

	@Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAScorecondition(this);
    }

    public TScore getScore()
    {
        return _score_;
    }

    public void setScore(TScore node)
    {
        if(_score_ != null)
        {
            _score_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _score_ = node;
    }

    public TFrom getFrom()
    {
        return _from_;
    }

    public void setFrom(TFrom node)
    {
        if(_from_ != null)
        {
            _from_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _from_ = node;
    }

    public TLPar getLPar()
    {
        return _lPar_;
    }

    public void setLPar(TLPar node)
    {
        if(_lPar_ != null)
        {
            _lPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lPar_ = node;
    }

    public PScorelist<?> getScorelist()
    {
        return _scorelist_;
    }

    public void setScorelist(PScorelist<?> node)
    {
        if(_scorelist_ != null)
        {
            _scorelist_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _scorelist_ = node;
    }

    public TRPar getRPar()
    {
        return _rPar_;
    }

    public void setRPar(TRPar node)
    {
        if(_rPar_ != null)
        {
            _rPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rPar_ = node;
    }

	@Override
    public String toString()
    {
        return ""
            + toString(_score_)
            + toString(_from_)
            + toString(_lPar_)
            + toString(_scorelist_)
            + toString(_rPar_);
    }

	@Override
    void removeChild(Node<?> child)
    {
        if(_score_ == child)
        {
            _score_ = null;
            return;
        }

        if(_from_ == child)
        {
            _from_ = null;
            return;
        }

        if(_lPar_ == child)
        {
            _lPar_ = null;
            return;
        }

        if(_scorelist_ == child)
        {
            _scorelist_ = null;
            return;
        }

        if(_rPar_ == child)
        {
            _rPar_ = null;
            return;
        }

    }

	@Override
    <U extends Node<U>> void replaceChild(U oldChild, U newChild)
    {
        if(_score_ == oldChild)
        {
            setScore((TScore) newChild);
            return;
        }

        if(_from_ == oldChild)
        {
            setFrom((TFrom) newChild);
            return;
        }

        if(_lPar_ == oldChild)
        {
            setLPar((TLPar) newChild);
            return;
        }

        if(_scorelist_ == oldChild)
        {
            setScorelist((PScorelist<?>) newChild);
            return;
        }

        if(_rPar_ == oldChild)
        {
            setRPar((TRPar) newChild);
            return;
        }

    }
}
