/**
Copyright 2017 Frontier Science & Technology Research Foundation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

ADDITIONAL DISCLAIMER:
In addition to the standard warranty exclusions and limitations of 
liability set forth in sections 7, 8 and 9 of the Apache 2.0 license 
that governs the use and development of this software, Frontier Science 
& Technology Research Foundation disclaims any liability for use of 
this software for patient care or in clinical settings. This software 
was developed solely for use in medical and public health research, and 
was not intended, designed, or validated to guide patient care.
*/ 



/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.fstrf.stanfordAsiInterpreter.resistance.grammar.node;

import java.util.*;
import org.fstrf.stanfordAsiInterpreter.resistance.grammar.analysis.*;

@SuppressWarnings("all") public final class AScorelist extends PScorelist
{
    private PScoreitem _scoreitem_;
    private final LinkedList _scoreitems_ = new TypedLinkedList(new Scoreitems_Cast());

    public AScorelist()
    {
    }

    public AScorelist(
        PScoreitem _scoreitem_,
        List _scoreitems_)
    {
        setScoreitem(_scoreitem_);

        {
            this._scoreitems_.clear();
            this._scoreitems_.addAll(_scoreitems_);
        }

    }
    public Object clone()
    {
        return new AScorelist(
            (PScoreitem) cloneNode(_scoreitem_),
            cloneList(_scoreitems_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAScorelist(this);
    }

    public PScoreitem getScoreitem()
    {
        return _scoreitem_;
    }

    public void setScoreitem(PScoreitem node)
    {
        if(_scoreitem_ != null)
        {
            _scoreitem_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _scoreitem_ = node;
    }

    public LinkedList getScoreitems()
    {
        return _scoreitems_;
    }

    public void setScoreitems(List list)
    {
        _scoreitems_.clear();
        _scoreitems_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_scoreitem_)
            + toString(_scoreitems_);
    }

    void removeChild(Node child)
    {
        if(_scoreitem_ == child)
        {
            _scoreitem_ = null;
            return;
        }

        if(_scoreitems_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_scoreitem_ == oldChild)
        {
            setScoreitem((PScoreitem) newChild);
            return;
        }

        for(ListIterator i = _scoreitems_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class Scoreitems_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PScoreitems node = (PScoreitems) o;

            if((node.parent() != null) &&
                (node.parent() != AScorelist.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AScorelist.this))
            {
                node.parent(AScorelist.this);
            }

            return node;
        }
    }
}
