/**
Copyright 2017 Frontier Science & Technology Research Foundation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

ADDITIONAL DISCLAIMER:
In addition to the standard warranty exclusions and limitations of 
liability set forth in sections 7, 8 and 9 of the Apache 2.0 license 
that governs the use and development of this software, Frontier Science 
& Technology Research Foundation disclaims any liability for use of 
this software for patient care or in clinical settings. This software 
was developed solely for use in medical and public health research, and 
was not intended, designed, or validated to guide patient care.
*/ 



/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.fstrf.stanfordAsiInterpreter.resistance.grammar.node;

import java.util.*;
import org.fstrf.stanfordAsiInterpreter.resistance.grammar.analysis.*;

public final class ASelectstatement extends PSelectstatement
{
    private TSelect _select_;
    private PSelectstatement2 _selectstatement2_;

    public ASelectstatement()
    {
    }

    public ASelectstatement(
        TSelect _select_,
        PSelectstatement2 _selectstatement2_)
    {
        setSelect(_select_);

        setSelectstatement2(_selectstatement2_);

    }
    public Object clone()
    {
        return new ASelectstatement(
            (TSelect) cloneNode(_select_),
            (PSelectstatement2) cloneNode(_selectstatement2_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASelectstatement(this);
    }

    public TSelect getSelect()
    {
        return _select_;
    }

    public void setSelect(TSelect node)
    {
        if(_select_ != null)
        {
            _select_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _select_ = node;
    }

    public PSelectstatement2 getSelectstatement2()
    {
        return _selectstatement2_;
    }

    public void setSelectstatement2(PSelectstatement2 node)
    {
        if(_selectstatement2_ != null)
        {
            _selectstatement2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _selectstatement2_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_select_)
            + toString(_selectstatement2_);
    }

    void removeChild(Node child)
    {
        if(_select_ == child)
        {
            _select_ = null;
            return;
        }

        if(_selectstatement2_ == child)
        {
            _selectstatement2_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_select_ == oldChild)
        {
            setSelect((TSelect) newChild);
            return;
        }

        if(_selectstatement2_ == oldChild)
        {
            setSelectstatement2((PSelectstatement2) newChild);
            return;
        }

    }
}
