/**
Copyright 2017 Frontier Science & Technology Research Foundation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

ADDITIONAL DISCLAIMER:
In addition to the standard warranty exclusions and limitations of 
liability set forth in sections 7, 8 and 9 of the Apache 2.0 license 
that governs the use and development of this software, Frontier Science 
& Technology Research Foundation disclaims any liability for use of 
this software for patient care or in clinical settings. This software 
was developed solely for use in medical and public health research, and 
was not intended, designed, or validated to guide patient care.
*/ 



/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.fstrf.stanfordAsiInterpreter.resistance.grammar.node;

import java.util.*;
import org.fstrf.stanfordAsiInterpreter.resistance.grammar.analysis.*;

@SuppressWarnings("all") public final class ASelectCondition extends PCondition
{
    private PSelectstatement _selectstatement_;

    public ASelectCondition()
    {
    }

    public ASelectCondition(
        PSelectstatement _selectstatement_)
    {
        setSelectstatement(_selectstatement_);

    }
    public Object clone()
    {
        return new ASelectCondition(
            (PSelectstatement) cloneNode(_selectstatement_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASelectCondition(this);
    }

    public PSelectstatement getSelectstatement()
    {
        return _selectstatement_;
    }

    public void setSelectstatement(PSelectstatement node)
    {
        if(_selectstatement_ != null)
        {
            _selectstatement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _selectstatement_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_selectstatement_);
    }

    void removeChild(Node child)
    {
        if(_selectstatement_ == child)
        {
            _selectstatement_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_selectstatement_ == oldChild)
        {
            setSelectstatement((PSelectstatement) newChild);
            return;
        }

    }
}
