/**
Copyright 2017 Frontier Science & Technology Research Foundation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

ADDITIONAL DISCLAIMER:
In addition to the standard warranty exclusions and limitations of 
liability set forth in sections 7, 8 and 9 of the Apache 2.0 license 
that governs the use and development of this software, Frontier Science 
& Technology Research Foundation disclaims any liability for use of 
this software for patient care or in clinical settings. This software 
was developed solely for use in medical and public health research, and 
was not intended, designed, or validated to guide patient care.
*/ 



/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.fstrf.stanfordAsiInterpreter.resistance.grammar.node;

import java.util.*;
import org.fstrf.stanfordAsiInterpreter.resistance.grammar.analysis.*;

@SuppressWarnings("all") public final class AStatementScoreitem extends PScoreitem
{
    private PBooleancondition _booleancondition_;
    private TMapper _mapper_;
    private TMin _min_;
    private PNumber _number_;

    public AStatementScoreitem()
    {
    }

    public AStatementScoreitem(
        PBooleancondition _booleancondition_,
        TMapper _mapper_,
        TMin _min_,
        PNumber _number_)
    {
        setBooleancondition(_booleancondition_);

        setMapper(_mapper_);

        setMin(_min_);

        setNumber(_number_);

    }
    public Object clone()
    {
        return new AStatementScoreitem(
            (PBooleancondition) cloneNode(_booleancondition_),
            (TMapper) cloneNode(_mapper_),
            (TMin) cloneNode(_min_),
            (PNumber) cloneNode(_number_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStatementScoreitem(this);
    }

    public PBooleancondition getBooleancondition()
    {
        return _booleancondition_;
    }

    public void setBooleancondition(PBooleancondition node)
    {
        if(_booleancondition_ != null)
        {
            _booleancondition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _booleancondition_ = node;
    }

    public TMapper getMapper()
    {
        return _mapper_;
    }

    public void setMapper(TMapper node)
    {
        if(_mapper_ != null)
        {
            _mapper_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _mapper_ = node;
    }

    public TMin getMin()
    {
        return _min_;
    }

    public void setMin(TMin node)
    {
        if(_min_ != null)
        {
            _min_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _min_ = node;
    }

    public PNumber getNumber()
    {
        return _number_;
    }

    public void setNumber(PNumber node)
    {
        if(_number_ != null)
        {
            _number_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _number_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_booleancondition_)
            + toString(_mapper_)
            + toString(_min_)
            + toString(_number_);
    }

    void removeChild(Node child)
    {
        if(_booleancondition_ == child)
        {
            _booleancondition_ = null;
            return;
        }

        if(_mapper_ == child)
        {
            _mapper_ = null;
            return;
        }

        if(_min_ == child)
        {
            _min_ = null;
            return;
        }

        if(_number_ == child)
        {
            _number_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_booleancondition_ == oldChild)
        {
            setBooleancondition((PBooleancondition) newChild);
            return;
        }

        if(_mapper_ == oldChild)
        {
            setMapper((TMapper) newChild);
            return;
        }

        if(_min_ == oldChild)
        {
            setMin((TMin) newChild);
            return;
        }

        if(_number_ == oldChild)
        {
            setNumber((PNumber) newChild);
            return;
        }

    }
}
