/**
Copyright 2017 Frontier Science & Technology Research Foundation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

ADDITIONAL DISCLAIMER:
In addition to the standard warranty exclusions and limitations of 
liability set forth in sections 7, 8 and 9 of the Apache 2.0 license 
that governs the use and development of this software, Frontier Science 
& Technology Research Foundation disclaims any liability for use of 
this software for patient care or in clinical settings. This software 
was developed solely for use in medical and public health research, and 
was not intended, designed, or validated to guide patient care.
*/ 



/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.fstrf.stanfordAsiInterpreter.resistance.grammar.node;

import org.fstrf.stanfordAsiInterpreter.resistance.grammar.analysis.Analysis;

public final class AStatementCondition extends PCondition<AStatementCondition>
{
    private TLPar _lPar_;
    private PBooleancondition<?> _booleancondition_;
    private TRPar _rPar_;

    public AStatementCondition()
    {
    }

    public AStatementCondition(
        TLPar _lPar_,
        PBooleancondition<?> _booleancondition_,
        TRPar _rPar_)
    {
        setLPar(_lPar_);

        setBooleancondition(_booleancondition_);

        setRPar(_rPar_);

    }

    @Override
    public AStatementCondition clone()
    {
        return new AStatementCondition(
            (TLPar) cloneNode(_lPar_),
            (PBooleancondition<?>) cloneNode(_booleancondition_),
            (TRPar) cloneNode(_rPar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStatementCondition(this);
    }

    public TLPar getLPar()
    {
        return _lPar_;
    }

    public void setLPar(TLPar node)
    {
        if(_lPar_ != null)
        {
            _lPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lPar_ = node;
    }

    public PBooleancondition<?> getBooleancondition()
    {
        return _booleancondition_;
    }

    public void setBooleancondition(PBooleancondition<?> node)
    {
        if(_booleancondition_ != null)
        {
            _booleancondition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _booleancondition_ = node;
    }

    public TRPar getRPar()
    {
        return _rPar_;
    }

    public void setRPar(TRPar node)
    {
        if(_rPar_ != null)
        {
            _rPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rPar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(_lPar_)
            + toString(_booleancondition_)
            + toString(_rPar_);
    }

    @Override
    void removeChild(Node<?> child)
    {
        if(_lPar_ == child)
        {
            _lPar_ = null;
            return;
        }

        if(_booleancondition_ == child)
        {
            _booleancondition_ = null;
            return;
        }

        if(_rPar_ == child)
        {
            _rPar_ = null;
            return;
        }

    }

    @Override
    <U extends Node<U>> void replaceChild(U oldChild, U newChild)
    {
        if(_lPar_ == oldChild)
        {
            setLPar((TLPar) newChild);
            return;
        }

        if(_booleancondition_ == oldChild)
        {
            setBooleancondition((PBooleancondition<?>) newChild);
            return;
        }

        if(_rPar_ == oldChild)
        {
            setRPar((TRPar) newChild);
            return;
        }

    }
}
