/**
Copyright 2017 Frontier Science & Technology Research Foundation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

ADDITIONAL DISCLAIMER:
In addition to the standard warranty exclusions and limitations of 
liability set forth in sections 7, 8 and 9 of the Apache 2.0 license 
that governs the use and development of this software, Frontier Science 
& Technology Research Foundation disclaims any liability for use of 
this software for patient care or in clinical settings. This software 
was developed solely for use in medical and public health research, and 
was not intended, designed, or validated to guide patient care.
*/ 



/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.fstrf.stanfordAsiInterpreter.resistance.grammar.node;

import java.util.*;

public class TypedLinkedList<T> extends LinkedList<T>
{
	private static final long serialVersionUID = 2105563691889628850L;
	Cast<T> cast;

    public TypedLinkedList()
    {
        super();

        cast = NoCast.instance();
    }

    public TypedLinkedList(Collection<T> c)
    {
        super(c);

        cast = NoCast.instance();
    }

    public TypedLinkedList(Cast<T> cast)
    {
        super();

        this.cast = cast;
    }

    public TypedLinkedList(Collection<T> c, Cast<T> cast)
    {
        super(c);

        this.cast = cast;
    }

    public Cast<T> getCast()
    {
        return cast;
    }

    @Override
    public void add(int index, T element)
    {
        super.add(index, cast.cast(element));
    }

    @Override
    public boolean add(T o)
    {
        return super.add(cast.cast(o));
    }

    @Override
    public boolean addAll(Collection<? extends T> c)
    {
        Object[] elements = c.toArray();
        for(int i=0; i<elements.length; i++)
        {
            super.add(cast.cast(elements[i]));
        }
        return true;
    }

    @Override
    public boolean addAll(int index, Collection<? extends T> c)
    {
        int pos = index;
        Object[] elements = c.toArray();
        for(int i=0; i<elements.length; i++)
        {
            super.add(pos++, cast.cast(elements[i]));
        }
        return true;
    }

    public void addFirst(Object o)
    {
        super.addFirst(cast.cast(o));
    }

    public void addLast(Object o)
    {
        super.addLast(cast.cast(o));
    }

    public ListIterator<T> listIterator(int index)
    {
        return new TypedLinkedListIterator(super.listIterator(index));
    }

    private class TypedLinkedListIterator implements ListIterator<T>
    {
        ListIterator<T> iterator;

        TypedLinkedListIterator(ListIterator<T> iterator)
        {
            this.iterator = iterator;
        }

        public boolean hasNext()
        {
            return iterator.hasNext();
        }

        public T next()
        {
            return iterator.next();
        }

        public boolean hasPrevious()
        {
            return iterator.hasPrevious();
        }

        public T previous()
        {
            return iterator.previous();
        }

        public int nextIndex()
        {
            return iterator.nextIndex();
        }

        public int previousIndex()
        {
            return iterator.previousIndex();
        }

        public void remove()
        {
            iterator.remove();
        }

        public void set(Object o)
        {
            iterator.set(cast.cast(o));
        }

        public void add(Object o)
        {
            iterator.add(cast.cast(o));
        }
    }
}
